name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: rustup update stable

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    
    - name: Install other Rust dependencies
      run: |
        rustup component add rustfmt clippy

    - name: Format check
      run: |
        cargo fmt --all -- --check
    
    - name: Run Clippy
      run: |
        cargo clippy

    - name: Builds
      run: |
        cargo build

    - name: Unit Test
      run: cargo llvm-cov

    - name: Integration Test
      run: make test